# Generated by Django 5.1.1 on 2024-10-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_staff_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('Customer Support', 'Customer Support'), ('Manager', 'Manager'), ('Admin', 'Admin')], max_length=20, null=True),
        ),
    ]
