# Generated by Django 5.1.1 on 2024-10-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_alter_complaint_assigned_to_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complaint_type',
            field=models.CharField(choices=[('Product Issue', 'Product Issue'), ('Billing Issue', 'Billing Issue'), ('Staff Behavior', 'Staff Behavior')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='open', max_length=50),
        ),
    ]
